/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Snapshot-style contract tests for build artifacts.
 *
 * RSS feed, sitemap, and search-index endpoints are consumed by external
 * clients (RSS readers, search engines, the iOS app, the in-page search).
 * Pin the contract — fields, schema shape, link forms — so we get a CI
 * red flag the moment the shape silently drifts.
 *
 * These tests don't snapshot byte-for-byte (content changes daily as new
 * posts ship) — they snapshot *structure*: types of fields, presence of
 * required keys, plausibility of values.
 */
import { test, expect } from './fixtures';

test.describe('RSS feed contract', () => {
  test('rss.xml is valid RSS 2.0 with channel + items', async ({ request }) => {
    const r = await request.get('/rss.xml');
    expect(r.status()).toBe(200);
    expect(r.headers()['content-type']).toMatch(/xml/);
    const body = await r.text();
    // RSS 2.0 envelope
    expect(body).toMatch(/<rss[^>]+version="2\.0"/);
    expect(body).toMatch(/<channel>/);
    expect(body).toMatch(/<title>/);
    expect(body).toMatch(/<link>/);
    expect(body).toMatch(/<description>/);
    // At least one item
    expect(body).toMatch(/<item>/);
    // Items have the required RSS 2.0 children
    const firstItem = body.match(/<item>([\s\S]*?)<\/item>/)?.[1] ?? '';
    expect(firstItem).toMatch(/<title>/);
    expect(firstItem).toMatch(/<link>/);
    expect(firstItem).toMatch(/<pubDate>/);
  });
});

test.describe('Sitemap contract', () => {
  test('sitemap-index.xml lists at least one sitemap', async ({ request }) => {
    const r = await request.get('/sitemap-index.xml');
    if (r.status() === 404) {
      test.skip(true, 'sitemap-index.xml only generated by `pnpm build` (not dev)');
    }
    expect(r.status()).toBe(200);
    const body = await r.text();
    expect(body).toMatch(/<sitemapindex/);
    expect(body).toMatch(/<sitemap>/);
    expect(body).toMatch(/<loc>/);
  });
});

test.describe('search-index contract', () => {
  test('zh-tw index has shape { ticketId, title, slug, lang, ... }', async ({ request }) => {
    const r = await request.get('/search-index.zh-tw.json');
    expect(r.status()).toBe(200);
    const arr = await r.json();
    expect(Array.isArray(arr)).toBe(true);
    expect(arr.length).toBeGreaterThan(50);

    const sample = arr.slice(0, 10);
    for (const entry of sample) {
      expect(typeof entry.title).toBe('string');
      expect(typeof entry.slug).toBe('string');
      expect(['zh-tw', 'en']).toContain(entry.lang);
    }
    // Every zh-tw entry should be lang=zh-tw
    expect(arr.every((e: any) => e.lang === 'zh-tw')).toBe(true);
  });

  test('en index lang field is uniformly "en"', async ({ request }) => {
    const r = await request.get('/search-index.en.json');
    const arr = await r.json();
    expect(arr.every((e: any) => e.lang === 'en')).toBe(true);
  });

  test('combined index covers both langs', async ({ request }) => {
    const r = await request.get('/search-index.json');
    const arr = await r.json();
    const langs = new Set(arr.map((e: any) => e.lang));
    expect(langs.has('zh-tw')).toBe(true);
    expect(langs.has('en')).toBe(true);
  });

  test('search-index titles are non-empty strings', async ({ request }) => {
    const r = await request.get('/search-index.zh-tw.json');
    const arr = await r.json();
    for (const e of arr.slice(0, 100)) {
      expect(typeof e.title).toBe('string');
      expect(e.title.length).toBeGreaterThan(0);
    }
  });
});

test.describe('feed.json contract — schema-pin (separate from /api/feed.json)', () => {
  test('static /api/feed.json has version: 1', async ({ request }) => {
    const r = await request.get('/api/feed.json');
    const body = await r.json();
    expect(body.version).toBe(1);
    expect(typeof body.count).toBe('number');
    expect(body.articles).toBeDefined();
  });
});
