/**
 * Read post version numbers from the pre-built manifest.
 * The manifest is generated by scripts/build-version-manifest.mjs
 * before each build (works regardless of git clone depth).
 */
import manifest from '../data/post-versions.json';

const versions: Record<string, number> = manifest as Record<string, number>;

export function getPostVersion(postId: string): string {
  // Astro post.id includes .mdx extension; manifest keys don't
  const key = postId.replace(/\.mdx$/, '');
  const count = versions[key];
  return count ? String(count) : '1';
}
