/**
 * Read post version numbers from the pre-built manifest.
 * The manifest is generated by scripts/build-version-manifest.mjs
 * before each build (works regardless of git clone depth).
 */
import manifest from '../data/post-versions.json';

const versions: Record<string, number> = manifest as Record<string, number>;

export function getPostVersion(postId: string): string {
  const count = versions[postId];
  return count ? String(count) : '1';
}
