#!/bin/bash
# Check for broken TOC in built HTML files
# A TOC is "broken" if:
# - .post-content has 2+ h2/h3 headings
# - BUT .toc-content is empty (no links generated)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DIST_DIR="$PROJECT_DIR/dist"

if [ ! -d "$DIST_DIR" ]; then
    echo "❌ dist/ not found. Run 'npm run build' first."
    exit 1
fi

echo "🔍 Checking TOC in built posts..."

BROKEN_COUNT=0
CHECKED_COUNT=0
WARNINGS=""

# Find all post HTML files
for html_file in "$DIST_DIR"/posts/*/index.html "$DIST_DIR"/en/posts/*/index.html; do
    [ -f "$html_file" ] || continue
    
    CHECKED_COUNT=$((CHECKED_COUNT + 1))
    
    # Extract content between post-content div and count h2/h3
    # Using awk to extract the relevant section
    HEADING_COUNT=$(awk '
        /class="post-content"/ { inside=1 }
        inside && /<h[23]/ { count++ }
        /<\/article>/ { inside=0 }
        END { print count+0 }
    ' "$html_file")
    
    # Check if toc-container exists
    HAS_TOC=$(grep -c 'toc-container' "$html_file" || echo "0")
    
    # Get relative path for display
    REL_PATH="${html_file#$DIST_DIR/}"
    
    if [ "$HEADING_COUNT" -ge 2 ] && [ "$HAS_TOC" -gt 0 ]; then
        # Has enough headings and has TOC container - should work
        : # silent pass
    elif [ "$HEADING_COUNT" -lt 2 ] && [ "$HAS_TOC" -gt 0 ]; then
        # Not enough headings but TOC exists - TOC should be hidden by JS
        WARNINGS="$WARNINGS\n  ⚠ $REL_PATH (h2/h3: $HEADING_COUNT, TOC should auto-hide)"
    elif [ "$HEADING_COUNT" -ge 2 ] && [ "$HAS_TOC" -eq 0 ]; then
        # Has headings but no TOC container - missing TOC component!
        echo "  ❌ $REL_PATH (h2/h3: $HEADING_COUNT, MISSING TOC COMPONENT!)"
        BROKEN_COUNT=$((BROKEN_COUNT + 1))
    fi
done

echo ""
echo "=========================================="
echo "Checked: $CHECKED_COUNT posts"

if [ -n "$WARNINGS" ]; then
    echo ""
    echo "Warnings (TOC will auto-hide, but low heading count):"
    echo -e "$WARNINGS"
fi

echo ""
if [ "$BROKEN_COUNT" -gt 0 ]; then
    echo "❌ Found $BROKEN_COUNT posts with missing TOC component!"
    exit 1
fi

echo "✓ All posts have TOC component!"
echo ""
echo "Note: TOC content is generated by client-side JS."
echo "To verify TOC actually works, check the live site."
exit 0
